import type { Template } from "@/types/database";

export const CATEGORIES = [
  "Landing Page",
  "Dashboard",
  "E-commerce",
  "Portfolio",
  "Blog",
  "SaaS",
] as const;

export const STYLES = [
  "Minimal",
  "Bold",
  "Gradient",
  "Glassmorphism",
  "Retro",
  "Corporate",
] as const;

export const PLATFORMS = ["Web", "iOS", "Android", "Figma"] as const;

export const MOCK_TEMPLATES: Template[] = [
  {
    id: "1",
    name: "Aurora Dashboard",
    slug: "aurora-dashboard",
    description:
      "A sleek, modern dashboard template with glassmorphism effects. Features dark mode, responsive charts, and a beautiful sidebar navigation.",
    category: "Dashboard",
    style: "Glassmorphism",
    platforms: ["Web", "Figma"],
    creator_id: "creator-1",
    price_tier: "pro",
    downloads_count: 1247,
    preview_url: "https://placehold.co/800x600/1a1a2e/e0e0e0?text=Aurora+Dashboard",
    preview_mobile_url: "https://placehold.co/400x800/1a1a2e/e0e0e0?text=Aurora+Mobile",
    manifest_json: null,
    tokens_json: null,
    status: "published",
    created_at: "2025-01-15T00:00:00Z",
    updated_at: "2025-01-15T00:00:00Z",
  },
  {
    id: "2",
    name: "Starter Landing",
    slug: "starter-landing",
    description:
      "Clean, minimal landing page perfect for launching your next SaaS product. Includes hero, features, pricing, and testimonials sections.",
    category: "Landing Page",
    style: "Minimal",
    platforms: ["Web"],
    creator_id: "creator-2",
    price_tier: "free",
    downloads_count: 3521,
    preview_url: "https://placehold.co/800x600/0a0a0a/e0e0e0?text=Starter+Landing",
    preview_mobile_url: null,
    manifest_json: null,
    tokens_json: null,
    status: "published",
    created_at: "2025-02-01T00:00:00Z",
    updated_at: "2025-02-01T00:00:00Z",
  },
  {
    id: "3",
    name: "Neon Commerce",
    slug: "neon-commerce",
    description:
      "Bold, vibrant e-commerce template with gradient accents and smooth animations. Perfect for fashion, tech, or lifestyle brands.",
    category: "E-commerce",
    style: "Gradient",
    platforms: ["Web", "iOS", "Android"],
    creator_id: "creator-1",
    price_tier: "pro",
    downloads_count: 892,
    preview_url: "https://placehold.co/800x600/16213e/e0e0e0?text=Neon+Commerce",
    preview_mobile_url: "https://placehold.co/400x800/16213e/e0e0e0?text=Neon+Mobile",
    manifest_json: null,
    tokens_json: null,
    status: "published",
    created_at: "2025-02-10T00:00:00Z",
    updated_at: "2025-02-10T00:00:00Z",
  },
  {
    id: "4",
    name: "Dev Portfolio",
    slug: "dev-portfolio",
    description:
      "Show off your work with this retro-inspired developer portfolio. Terminal-style animations, project showcase, and blog section.",
    category: "Portfolio",
    style: "Retro",
    platforms: ["Web"],
    creator_id: "creator-3",
    price_tier: "free",
    downloads_count: 2103,
    preview_url: "https://placehold.co/800x600/1a1a1a/00ff00?text=Dev+Portfolio",
    preview_mobile_url: null,
    manifest_json: null,
    tokens_json: null,
    status: "published",
    created_at: "2025-02-20T00:00:00Z",
    updated_at: "2025-02-20T00:00:00Z",
  },
  {
    id: "5",
    name: "Blogify",
    slug: "blogify",
    description:
      "A clean, content-focused blog template with beautiful typography, dark/light modes, and MDX support built-in.",
    category: "Blog",
    style: "Minimal",
    platforms: ["Web"],
    creator_id: "creator-2",
    price_tier: "free",
    downloads_count: 1876,
    preview_url: "https://placehold.co/800x600/111111/e0e0e0?text=Blogify",
    preview_mobile_url: null,
    manifest_json: null,
    tokens_json: null,
    status: "published",
    created_at: "2025-03-01T00:00:00Z",
    updated_at: "2025-03-01T00:00:00Z",
  },
  {
    id: "6",
    name: "SaaS Kit Pro",
    slug: "saas-kit-pro",
    description:
      "Complete SaaS starter with auth, billing, dashboards, and settings. Corporate design that inspires trust.",
    category: "SaaS",
    style: "Corporate",
    platforms: ["Web", "Figma"],
    creator_id: "creator-1",
    price_tier: "pro",
    downloads_count: 654,
    preview_url: "https://placehold.co/800x600/0f172a/e0e0e0?text=SaaS+Kit+Pro",
    preview_mobile_url: "https://placehold.co/400x800/0f172a/e0e0e0?text=SaaS+Mobile",
    manifest_json: null,
    tokens_json: null,
    status: "published",
    created_at: "2025-03-10T00:00:00Z",
    updated_at: "2025-03-10T00:00:00Z",
  },
  {
    id: "7",
    name: "Gradient Hero",
    slug: "gradient-hero",
    description:
      "Stunning gradient-heavy landing page with bold typography and smooth scroll animations. Great for product launches.",
    category: "Landing Page",
    style: "Bold",
    platforms: ["Web", "Figma"],
    creator_id: "creator-3",
    price_tier: "pro",
    downloads_count: 445,
    preview_url: "https://placehold.co/800x600/2d1b69/e0e0e0?text=Gradient+Hero",
    preview_mobile_url: null,
    manifest_json: null,
    tokens_json: null,
    status: "published",
    created_at: "2025-03-15T00:00:00Z",
    updated_at: "2025-03-15T00:00:00Z",
  },
  {
    id: "8",
    name: "Glass Dashboard",
    slug: "glass-dashboard",
    description:
      "A frosted glass-style analytics dashboard with real-time chart components and responsive data tables.",
    category: "Dashboard",
    style: "Glassmorphism",
    platforms: ["Web"],
    creator_id: "creator-2",
    price_tier: "pro",
    downloads_count: 723,
    preview_url: "https://placehold.co/800x600/1e1e2e/e0e0e0?text=Glass+Dashboard",
    preview_mobile_url: "https://placehold.co/400x800/1e1e2e/e0e0e0?text=Glass+Mobile",
    manifest_json: null,
    tokens_json: null,
    status: "published",
    created_at: "2025-03-20T00:00:00Z",
    updated_at: "2025-03-20T00:00:00Z",
  },
];
