import type { Template } from "@/types/database";

export const CATEGORIES = [
  "Landing Page",
  "Dashboard",
  "E-commerce",
  "Portfolio",
  "Blog",
  "SaaS",
] as const;

export const STYLES = [
  "Minimal",
  "Bold",
  "Gradient",
  "Glassmorphism",
  "Retro",
  "Corporate",
  "Brutalist",
  "Neomorphic",
] as const;

export const PLATFORMS = ["Web", "iOS", "Android", "Figma"] as const;

export const MOCK_TEMPLATES: Template[] = [
  {
    id: "1",
    name: "SaaS Minimalist",
    slug: "saas-minimalist",
    description:
      "A clean, whitespace-heavy SaaS landing page with subtle animations. Features hero with product mockup, feature grid, testimonials carousel, pricing table, and a beautiful CTA section. Built with accessibility-first approach.",
    category: "SaaS",
    style: "Minimal",
    platforms: ["Web", "Figma"],
    creator_id: "creator-1",
    price_tier: "pro",
    downloads_count: 3847,
    preview_url: "https://placehold.co/800x600/0a0a0a/f5f5f5?text=SaaS+Minimalist",
    preview_mobile_url: "https://placehold.co/400x800/0a0a0a/f5f5f5?text=SaaS+Mobile",
    manifest_json: null,
    tokens_json: null,
    status: "published",
    created_at: "2025-01-10T00:00:00Z",
    updated_at: "2025-03-01T00:00:00Z",
  },
  {
    id: "2",
    name: "Portfolio Brutalist",
    slug: "portfolio-brutalist",
    description:
      "Raw, unapologetic portfolio template with exposed grid systems, monospaced typography, and deliberate anti-design elements. Features project showcase with full-bleed images, manifesto section, and contact form.",
    category: "Portfolio",
    style: "Brutalist",
    platforms: ["Web"],
    creator_id: "creator-2",
    price_tier: "free",
    downloads_count: 2156,
    preview_url: "https://placehold.co/800x600/f5f5f5/0a0a0a?text=Portfolio+Brutalist",
    preview_mobile_url: null,
    manifest_json: null,
    tokens_json: null,
    status: "published",
    created_at: "2025-01-20T00:00:00Z",
    updated_at: "2025-02-15T00:00:00Z",
  },
  {
    id: "3",
    name: "Aurora Dashboard",
    slug: "aurora-dashboard",
    description:
      "Premium analytics dashboard with glassmorphic panels, real-time data visualization, and a stunning dark theme. Includes 12+ chart types, data tables, kanban board, and notification center. Fully responsive.",
    category: "Dashboard",
    style: "Glassmorphism",
    platforms: ["Web", "Figma"],
    creator_id: "creator-1",
    price_tier: "pro",
    downloads_count: 5203,
    preview_url: "https://placehold.co/800x600/0f0f23/a78bfa?text=Aurora+Dashboard",
    preview_mobile_url: "https://placehold.co/400x800/0f0f23/a78bfa?text=Aurora+Mobile",
    manifest_json: null,
    tokens_json: null,
    status: "published",
    created_at: "2025-02-01T00:00:00Z",
    updated_at: "2025-03-10T00:00:00Z",
  },
  {
    id: "4",
    name: "Neon Commerce",
    slug: "neon-commerce",
    description:
      "Electric e-commerce storefront with vibrant gradient accents and smooth micro-interactions. Product grid with quick view, cart drawer, wishlist, and checkout flow. Built for fashion, sneakers, and streetwear brands.",
    category: "E-commerce",
    style: "Gradient",
    platforms: ["Web", "iOS", "Android"],
    creator_id: "creator-3",
    price_tier: "pro",
    downloads_count: 1892,
    preview_url: "https://placehold.co/800x600/0a0a1a/06b6d4?text=Neon+Commerce",
    preview_mobile_url: "https://placehold.co/400x800/0a0a1a/06b6d4?text=Neon+Mobile",
    manifest_json: null,
    tokens_json: null,
    status: "published",
    created_at: "2025-02-10T00:00:00Z",
    updated_at: "2025-03-05T00:00:00Z",
  },
  {
    id: "5",
    name: "Terminal Folio",
    slug: "terminal-folio",
    description:
      "Developer portfolio inspired by terminal aesthetics. Monospaced type, command-line animations, ASCII art headers, and a matrix-rain easter egg. Project cards look like terminal windows. Dark only.",
    category: "Portfolio",
    style: "Retro",
    platforms: ["Web"],
    creator_id: "creator-2",
    price_tier: "free",
    downloads_count: 4721,
    preview_url: "https://placehold.co/800x600/0d1117/22c55e?text=%3E_+Terminal+Folio",
    preview_mobile_url: null,
    manifest_json: null,
    tokens_json: null,
    status: "published",
    created_at: "2025-02-15T00:00:00Z",
    updated_at: "2025-02-28T00:00:00Z",
  },
  {
    id: "6",
    name: "Gradient Hero",
    slug: "gradient-hero",
    description:
      "Show-stopping landing page with mesh gradient hero, animated blob backgrounds, and bold typography. Sections for features, social proof, integrations grid, FAQ accordion, and waitlist signup. Conversion-optimized.",
    category: "Landing Page",
    style: "Gradient",
    platforms: ["Web", "Figma"],
    creator_id: "creator-1",
    price_tier: "pro",
    downloads_count: 2934,
    preview_url: "https://placehold.co/800x600/1e1b4b/c084fc?text=Gradient+Hero",
    preview_mobile_url: "https://placehold.co/400x800/1e1b4b/c084fc?text=Gradient+Mobile",
    manifest_json: null,
    tokens_json: null,
    status: "published",
    created_at: "2025-02-20T00:00:00Z",
    updated_at: "2025-03-12T00:00:00Z",
  },
  {
    id: "7",
    name: "Blogify Pro",
    slug: "blogify-pro",
    description:
      "Content-first blog template with gorgeous typography, reading progress bar, estimated read time, table of contents sidebar, code syntax highlighting, and newsletter signup. Supports MDX out of the box.",
    category: "Blog",
    style: "Minimal",
    platforms: ["Web"],
    creator_id: "creator-3",
    price_tier: "free",
    downloads_count: 3156,
    preview_url: "https://placehold.co/800x600/18181b/fafafa?text=Blogify+Pro",
    preview_mobile_url: null,
    manifest_json: null,
    tokens_json: null,
    status: "published",
    created_at: "2025-03-01T00:00:00Z",
    updated_at: "2025-03-15T00:00:00Z",
  },
  {
    id: "8",
    name: "Enterprise Suite",
    slug: "enterprise-suite",
    description:
      "Corporate SaaS template suite with admin dashboard, user management, role-based access, audit logs, and settings. Clean, professional design with data density focus. Includes light and dark modes.",
    category: "SaaS",
    style: "Corporate",
    platforms: ["Web", "Figma"],
    creator_id: "creator-1",
    price_tier: "pro",
    downloads_count: 1547,
    preview_url: "https://placehold.co/800x600/0f172a/94a3b8?text=Enterprise+Suite",
    preview_mobile_url: "https://placehold.co/400x800/0f172a/94a3b8?text=Enterprise+Mobile",
    manifest_json: null,
    tokens_json: null,
    status: "published",
    created_at: "2025-03-05T00:00:00Z",
    updated_at: "2025-03-18T00:00:00Z",
  },
  {
    id: "9",
    name: "Starter Landing",
    slug: "starter-landing",
    description:
      "The perfect first impression. Minimal landing page with animated hero text, feature bento grid, testimonial wall, pricing toggle, and clean footer. Optimized for conversions with A/B test friendly sections.",
    category: "Landing Page",
    style: "Minimal",
    platforms: ["Web"],
    creator_id: "creator-2",
    price_tier: "free",
    downloads_count: 6842,
    preview_url: "https://placehold.co/800x600/09090b/e4e4e7?text=Starter+Landing",
    preview_mobile_url: null,
    manifest_json: null,
    tokens_json: null,
    status: "published",
    created_at: "2025-03-08T00:00:00Z",
    updated_at: "2025-03-20T00:00:00Z",
  },
  {
    id: "10",
    name: "Soft Dashboard",
    slug: "soft-dashboard",
    description:
      "Neomorphic admin dashboard with soft shadows, pill-shaped controls, and pastel accents on dark backgrounds. Features project tracker, team activity feed, file manager, and calendar view. Touch-friendly.",
    category: "Dashboard",
    style: "Neomorphic",
    platforms: ["Web", "iOS", "Android", "Figma"],
    creator_id: "creator-3",
    price_tier: "pro",
    downloads_count: 1203,
    preview_url: "https://placehold.co/800x600/1a1a2e/e879f9?text=Soft+Dashboard",
    preview_mobile_url: "https://placehold.co/400x800/1a1a2e/e879f9?text=Soft+Mobile",
    manifest_json: null,
    tokens_json: null,
    status: "published",
    created_at: "2025-03-12T00:00:00Z",
    updated_at: "2025-03-22T00:00:00Z",
  },
];
