export default function SaaSBrutalistDemo() {
  return (
    <div className="min-h-screen bg-white" style={{ fontFamily: "Space Mono, monospace" }}>
      <link href="https://fonts.googleapis.com/css2?family=Space+Mono:wght@400;700&display=swap" rel="stylesheet" />
      <nav className="border-b-4 border-black"><div className="max-w-6xl mx-auto px-4 h-16 flex items-center justify-between"><span className="text-xl font-bold text-black uppercase tracking-wider">ACME_</span><div className="hidden md:flex space-x-6"><span className="text-sm text-black uppercase font-bold hover:bg-yellow-300 px-2 cursor-pointer">Product</span><span className="text-sm text-black uppercase font-bold hover:bg-yellow-300 px-2 cursor-pointer">Features</span><span className="text-sm text-black uppercase font-bold hover:bg-yellow-300 px-2 cursor-pointer">Pricing</span></div><button className="h-10 px-6 text-sm font-bold text-white bg-black hover:bg-yellow-300 hover:text-black border-2 border-black uppercase tracking-wider transition-colors">Enter</button></div></nav>
      <section className="max-w-6xl mx-auto px-4 py-24"><div className="border-4 border-black p-2 inline-block bg-yellow-300 mb-8"><span className="text-sm font-bold uppercase">New: v2.0</span></div><h1 className="text-7xl font-bold text-black leading-none mb-6 uppercase">SHIP<br/>FAST.<br/>BREAK<br/>NOTHING.</h1><p className="text-lg text-black max-w-xl mb-8 border-l-4 border-black pl-4">Raw power for teams who don&apos;t need decoration.</p><div className="flex space-x-4"><button className="h-12 px-8 text-sm font-bold text-white bg-black hover:bg-yellow-300 hover:text-black border-2 border-black uppercase tracking-wider transition-colors">Start now</button><button className="h-12 px-8 text-sm font-bold text-black bg-white hover:bg-yellow-300 border-2 border-black uppercase tracking-wider transition-colors">Read docs</button></div></section>
      <section className="max-w-6xl mx-auto px-4 py-16"><div className="grid grid-cols-1 md:grid-cols-3 gap-0">{[{t:"RAW SPEED",d:"No bloat. Pure performance.",n:"01"},{t:"ZERO CONFIG",d:"It works or it doesn't.",n:"02"},{t:"OPEN SOURCE",d:"Read every line. Fork it.",n:"03"}].map((f)=>(<div key={f.t} className="border-2 border-black p-8 hover:bg-yellow-300 transition-colors"><span className="text-6xl font-bold text-black opacity-20">{f.n}</span><h3 className="text-lg font-bold text-black uppercase mt-4 mb-2">{f.t}</h3><p className="text-sm text-black">{f.d}</p></div>))}</div></section>
      <section className="max-w-6xl mx-auto px-4 py-16"><h2 className="text-4xl font-bold text-black uppercase mb-12 border-b-4 border-black pb-4">Pricing_</h2><div className="grid grid-cols-1 md:grid-cols-2 gap-0 max-w-3xl"><div className="border-2 border-black p-8"><h3 className="text-lg font-bold text-black uppercase">Free_</h3><div className="mt-4 mb-6"><span className="text-5xl font-bold text-black">$0</span></div><ul className="space-y-2 mb-8 text-sm text-black font-bold"><li>→ 3 projects</li><li>→ Basic CLI</li><li>→ Community</li></ul><button className="w-full h-10 text-sm font-bold text-black bg-white hover:bg-yellow-300 border-2 border-black uppercase transition-colors">Get started</button></div><div className="border-2 border-black border-l-0 p-8 bg-black text-white"><h3 className="text-lg font-bold uppercase">Pro_</h3><div className="mt-4 mb-6"><span className="text-5xl font-bold">$29</span></div><ul className="space-y-2 mb-8 text-sm font-bold"><li>→ Unlimited</li><li>→ Full API</li><li>→ Priority</li></ul><button className="w-full h-10 text-sm font-bold text-black bg-yellow-300 hover:bg-white border-2 border-yellow-300 uppercase transition-colors">Go pro</button></div></div></section>
      <footer className="border-t-4 border-black mt-16"><div className="max-w-6xl mx-auto px-4 py-8"><span className="text-sm text-black font-bold uppercase">© 2026 ACME_</span></div></footer>
    </div>
  )
}
