export default function SaaSLuxuryDemo() {
  return (
    <div className="min-h-screen bg-stone-950" style={{ fontFamily: "Cormorant Garamond, serif" }}>
      <link href="https://fonts.googleapis.com/css2?family=Cormorant+Garamond:wght@300;400;600&family=Outfit:wght@300;400&display=swap" rel="stylesheet" />
      <nav className="border-b border-stone-800"><div className="max-w-6xl mx-auto px-4 h-20 flex items-center justify-between"><span className="text-2xl font-light text-amber-200 tracking-[0.3em] uppercase">Aurum</span><div className="hidden md:flex space-x-10"><span className="text-xs text-stone-400 hover:text-amber-200 cursor-pointer transition-colors tracking-[0.2em] uppercase" style={{fontFamily:"Outfit"}}>Collection</span><span className="text-xs text-stone-400 hover:text-amber-200 cursor-pointer transition-colors tracking-[0.2em] uppercase" style={{fontFamily:"Outfit"}}>Experience</span><span className="text-xs text-stone-400 hover:text-amber-200 cursor-pointer transition-colors tracking-[0.2em] uppercase" style={{fontFamily:"Outfit"}}>Membership</span></div><button className="h-10 px-8 text-xs text-amber-200 border border-amber-200/30 hover:bg-amber-200 hover:text-stone-950 tracking-[0.2em] uppercase transition-all" style={{fontFamily:"Outfit"}}>Reserve</button></div></nav>
      <section className="max-w-5xl mx-auto px-4 py-32 text-center"><div className="text-xs text-amber-200/60 tracking-[0.4em] uppercase mb-8" style={{fontFamily:"Outfit"}}>Exclusive Access</div><h1 className="text-7xl font-light text-white mb-8 leading-tight tracking-tight">Where Vision<br/>Meets <em className="text-amber-200">Excellence</em></h1><p className="text-lg text-stone-400 max-w-xl mx-auto mb-12 font-light leading-relaxed" style={{fontFamily:"Outfit"}}>An unparalleled platform for those who demand nothing less than extraordinary.</p><button className="h-14 px-12 text-xs text-stone-950 bg-amber-200 hover:bg-amber-100 tracking-[0.2em] uppercase transition-colors" style={{fontFamily:"Outfit"}}>Begin your journey</button></section>
      <section className="max-w-6xl mx-auto px-4 py-16"><div className="grid grid-cols-1 md:grid-cols-3 gap-px bg-stone-800">{[{t:"Curated",d:"Every detail handpicked by artisans.",n:"I"},{t:"Bespoke",d:"Tailored to your unique requirements.",n:"II"},{t:"Timeless",d:"Built to endure beyond trends.",n:"III"}].map((f)=>(<div key={f.t} className="bg-stone-950 p-12 text-center"><span className="text-3xl text-amber-200/40 font-light">{f.n}</span><h3 className="text-xl font-light text-white mt-6 mb-4 tracking-wider">{f.t}</h3><p className="text-sm text-stone-500 font-light" style={{fontFamily:"Outfit"}}>{f.d}</p></div>))}</div></section>
      <section className="max-w-4xl mx-auto px-4 py-20 text-center"><h2 className="text-4xl font-light text-white mb-4 tracking-tight">Membership</h2><p className="text-stone-500 mb-16" style={{fontFamily:"Outfit"}}>By invitation or application</p><div className="grid grid-cols-1 md:grid-cols-2 gap-px bg-stone-800 max-w-3xl mx-auto"><div className="bg-stone-950 p-12"><h3 className="text-lg font-light text-white tracking-wider">Atelier</h3><div className="mt-6 mb-8"><span className="text-5xl font-light text-white">$99</span><span className="text-stone-500 text-sm" style={{fontFamily:"Outfit"}}>/month</span></div><ul className="space-y-3 mb-10 text-sm text-stone-500" style={{fontFamily:"Outfit"}}><li>Private collection</li><li>Concierge support</li><li>Quarterly reviews</li></ul><button className="w-full h-10 text-xs text-amber-200 border border-amber-200/30 hover:bg-amber-200 hover:text-stone-950 tracking-[0.2em] uppercase transition-all" style={{fontFamily:"Outfit"}}>Apply</button></div><div className="bg-stone-900 p-12"><h3 className="text-lg font-light text-amber-200 tracking-wider">Maison</h3><div className="mt-6 mb-8"><span className="text-5xl font-light text-amber-200">$499</span><span className="text-stone-500 text-sm" style={{fontFamily:"Outfit"}}>/month</span></div><ul className="space-y-3 mb-10 text-sm text-stone-400" style={{fontFamily:"Outfit"}}><li>Everything in Atelier</li><li>Dedicated strategist</li><li>White-glove onboarding</li></ul><button className="w-full h-10 text-xs text-stone-950 bg-amber-200 hover:bg-amber-100 tracking-[0.2em] uppercase transition-all" style={{fontFamily:"Outfit"}}>Apply</button></div></div></section>
      <footer className="border-t border-stone-800 mt-16"><div className="max-w-6xl mx-auto px-4 py-10 text-center"><span className="text-xs text-stone-600 tracking-[0.3em] uppercase" style={{fontFamily:"Outfit"}}>© 2026 Aurum</span></div></footer>
    </div>
  )
}
