export default function StartupPlayfulDemo() {
  return (
    <div className="min-h-screen bg-slate-50" style={{fontFamily:"Nunito, sans-serif"}}>
      <link href="https://fonts.googleapis.com/css2?family=Nunito:wght@400;600;700;800&display=swap" rel="stylesheet"/>
      <nav className="bg-white/80 backdrop-blur-sm border-b border-slate-200"><div className="max-w-6xl mx-auto px-4 h-16 flex items-center justify-between"><span className="text-xl font-extrabold text-transparent bg-clip-text bg-gradient-to-r from-cyan-500 to-purple-600">launchly</span><div className="hidden md:flex space-x-6"><span className="text-sm font-semibold text-slate-600 hover:text-cyan-600 cursor-pointer">Features</span><span className="text-sm font-semibold text-slate-600 hover:text-cyan-600 cursor-pointer">Pricing</span><span className="text-sm font-semibold text-slate-600 hover:text-cyan-600 cursor-pointer">Blog</span></div><button className="h-10 px-6 text-sm font-bold text-white bg-gradient-to-r from-cyan-500 to-purple-600 rounded-full shadow-lg">Get started 🚀</button></div></nav>
      <section className="max-w-6xl mx-auto px-4 py-24 text-center"><div className="inline-flex items-center px-4 py-2 rounded-full bg-cyan-50 text-cyan-700 text-sm font-bold mb-6">🎯 Backed by Y Combinator</div><h1 className="text-6xl font-extrabold text-slate-900 mb-6 leading-tight">Launch your idea<br/>in <span className="text-transparent bg-clip-text bg-gradient-to-r from-cyan-500 to-purple-600">days, not months</span></h1><p className="text-lg text-slate-600 max-w-xl mx-auto mb-8 font-medium">The all-in-one platform that takes you from idea to paying customers. No code required. 💪</p><div className="flex justify-center space-x-3"><button className="h-12 px-8 text-sm font-bold text-white bg-gradient-to-r from-cyan-500 to-purple-600 rounded-full shadow-lg">Start free trial ✨</button><button className="h-12 px-8 text-sm font-bold text-slate-700 bg-white border-2 border-slate-200 rounded-full">See it in action 📺</button></div><div className="flex justify-center items-center space-x-6 mt-10 text-sm text-slate-500 font-semibold"><span>⭐ 4.9/5 on G2</span><span>🏆 #1 on Product Hunt</span><span>💜 10K+ teams</span></div></section>
      <section className="max-w-6xl mx-auto px-4 py-16"><div className="grid grid-cols-1 md:grid-cols-3 gap-6">{[{t:"Landing pages 🎨",d:"Beautiful, converting pages in minutes. No designer needed.",bg:"bg-cyan-50 border-cyan-200"},{t:"Payments 💳",d:"Stripe integration built in. Start earning from day one.",bg:"bg-purple-50 border-purple-200"},{t:"Analytics 📈",d:"Know exactly what works. Real-time dashboards you&apos;ll love.",bg:"bg-pink-50 border-pink-200"}].map((f)=>(<div key={f.t} className={`rounded-2xl p-6 border-2 ${f.bg}`}><h3 className="text-lg font-extrabold text-slate-900 mb-2">{f.t}</h3><p className="text-sm text-slate-600 font-medium">{f.d}</p></div>))}</div></section>
      <section className="max-w-6xl mx-auto px-4 py-16"><h2 className="text-3xl font-extrabold text-slate-900 text-center mb-12">Loved by founders 💜</h2><div className="grid grid-cols-1 md:grid-cols-3 gap-6">{[{q:"Launched in 3 days. Got our first 100 users in a week!",n:"Sarah K.",r:"CEO, Flowbase"},{q:"Replaced 5 tools. Our team saves 20 hours a week.",n:"Marcus T.",r:"CTO, Pixelforge"},{q:"The pricing page alone increased our conversions 40%.",n:"Priya M.",r:"Founder, Novalink"}].map((t)=>(<div key={t.n} className="bg-white rounded-2xl p-6 border border-slate-200 shadow-sm"><p className="text-sm text-slate-600 font-medium mb-4">&quot;{t.q}&quot;</p><div className="flex items-center space-x-3"><div className="w-10 h-10 rounded-full bg-gradient-to-r from-cyan-400 to-purple-500"></div><div><p className="text-sm font-bold text-slate-900">{t.n}</p><p className="text-xs text-slate-500">{t.r}</p></div></div></div>))}</div></section>
      <section className="max-w-6xl mx-auto px-4 py-16"><h2 className="text-3xl font-extrabold text-slate-900 text-center mb-4">Simple pricing 💰</h2><p className="text-slate-600 text-center mb-12 font-medium">Start free, upgrade when you&apos;re ready.</p><div className="grid grid-cols-1 md:grid-cols-2 gap-6 max-w-3xl mx-auto"><div className="bg-white rounded-2xl p-8 border-2 border-slate-200"><h3 className="text-lg font-extrabold text-slate-900">Starter 🌱</h3><div className="mt-4 mb-6"><span className="text-4xl font-extrabold text-slate-900">$0</span><span className="text-slate-500 font-semibold">/mo</span></div><ul className="space-y-3 mb-8 text-sm text-slate-600 font-semibold"><li>✅ 1 project</li><li>✅ Basic analytics</li><li>✅ Community support</li></ul><button className="w-full h-10 text-sm font-bold text-slate-700 bg-slate-100 rounded-full">Get started</button></div><div className="bg-gradient-to-br from-cyan-500 to-purple-600 rounded-2xl p-8 text-white shadow-xl"><h3 className="text-lg font-extrabold">Growth 🚀</h3><div className="mt-4 mb-6"><span className="text-4xl font-extrabold">$29</span><span className="text-cyan-200 font-semibold">/mo</span></div><ul className="space-y-3 mb-8 text-sm font-semibold text-cyan-100"><li>🎯 Unlimited projects</li><li>📊 Advanced analytics</li><li>⚡ Priority support</li></ul><button className="w-full h-10 text-sm font-bold text-purple-700 bg-white rounded-full">Start free trial</button></div></div></section>
      <footer className="bg-slate-900 mt-16"><div className="max-w-6xl mx-auto px-4 py-8 text-center"><span className="text-sm text-slate-400 font-semibold">© 2026 launchly · Built with 💜 for founders everywhere</span></div></footer>
    </div>
  )
}
