export default function RestaurantLuxuryDemo() {
  return (
    <div className="min-h-screen bg-stone-950 text-stone-200" style={{fontFamily:"Cormorant Garamond, serif"}}>
      <link href="https://fonts.googleapis.com/css2?family=Cormorant+Garamond:wght@300;400;600&family=Outfit:wght@300;400&display=swap" rel="stylesheet"/>
      <nav className="border-b border-stone-800"><div className="max-w-5xl mx-auto px-4 h-20 flex items-center justify-between"><span className="text-2xl font-light text-amber-200 tracking-[0.3em] uppercase">Lumière</span><div className="hidden md:flex space-x-10"><span className="text-xs text-stone-400 tracking-[0.2em] uppercase cursor-pointer hover:text-amber-200" style={{fontFamily:"Outfit"}}>Menu</span><span className="text-xs text-stone-400 tracking-[0.2em] uppercase cursor-pointer hover:text-amber-200" style={{fontFamily:"Outfit"}}>Story</span><span className="text-xs text-stone-400 tracking-[0.2em] uppercase cursor-pointer hover:text-amber-200" style={{fontFamily:"Outfit"}}>Events</span></div><button className="h-10 px-8 text-xs text-amber-200 border border-amber-200/30 hover:bg-amber-200 hover:text-stone-950 tracking-[0.2em] uppercase transition-all" style={{fontFamily:"Outfit"}}>Reserve</button></div></nav>
      <section className="max-w-4xl mx-auto px-4 py-32 text-center"><div className="text-xs text-amber-200/60 tracking-[0.4em] uppercase mb-8" style={{fontFamily:"Outfit"}}>Two Michelin Stars</div><h1 className="text-7xl font-light text-white leading-tight">A Journey<br/>Through <em className="text-amber-200">Flavor</em></h1><p className="text-lg text-stone-400 max-w-md mx-auto mt-8 font-light" style={{fontFamily:"Outfit"}}>Where each course tells a story, and every evening becomes a memory.</p></section>
      <section className="max-w-3xl mx-auto px-4 py-16"><h2 className="text-3xl font-light text-center text-white mb-2">Tasting Menu</h2><p className="text-center text-stone-500 mb-16" style={{fontFamily:"Outfit"}}>Seven courses · Seasonal ingredients</p><div className="space-y-8">{[{d:"Hamachi Crudo",s:"yuzu kosho · shiso · finger lime",p:"—"},{d:"Foie Gras Torchon",s:"brioche · sauternes gelée · black truffle",p:"—"},{d:"Lobster Bisque",s:"tarragon cream · cognac · puff pastry",p:"—"},{d:"Wagyu A5 Tenderloin",s:"bone marrow jus · pomme purée · seasonal root",p:"—"},{d:"Cheese Selection",s:"aged comté · stilton · local chèvre",p:"—"},{d:"Chocolate Soufflé",s:"grand marnier · crème anglaise · gold leaf",p:"—"}].map((i)=>(<div key={i.d} className="flex justify-between items-baseline border-b border-stone-800 pb-4"><div><h3 className="text-xl font-light text-white">{i.d}</h3><p className="text-sm text-stone-500 mt-1" style={{fontFamily:"Outfit"}}>{i.s}</p></div></div>))}</div><div className="text-center mt-12"><p className="text-2xl font-light text-amber-200">$285 <span className="text-sm text-stone-500" style={{fontFamily:"Outfit"}}>per person</span></p><p className="text-xs text-stone-600 mt-2" style={{fontFamily:"Outfit"}}>Wine pairing available · $165 supplement</p></div></section>
      <section className="max-w-4xl mx-auto px-4 py-20 text-center"><button className="h-14 px-16 text-xs text-stone-950 bg-amber-200 hover:bg-amber-100 tracking-[0.2em] uppercase transition-colors" style={{fontFamily:"Outfit"}}>Reserve your table</button><p className="text-xs text-stone-600 mt-6" style={{fontFamily:"Outfit"}}>Tuesday – Saturday · 6:00 PM – 10:30 PM</p></section>
      <footer className="border-t border-stone-800"><div className="max-w-5xl mx-auto px-4 py-10 text-center"><span className="text-xs text-stone-600 tracking-[0.3em] uppercase" style={{fontFamily:"Outfit"}}>© 2026 Lumière · 42 Rue de Rivoli, Paris</span></div></footer>
    </div>
  )
}
