export default function SaaSCorporateDemo() {
  return (
    <div className="min-h-screen bg-slate-50" style={{ fontFamily: "IBM Plex Sans, sans-serif" }}>
      <link href="https://fonts.googleapis.com/css2?family=IBM+Plex+Sans:wght@300;400;500;600;700&display=swap" rel="stylesheet" />
      <nav className="bg-white border-b border-slate-200 shadow-sm"><div className="max-w-7xl mx-auto px-6 h-20 flex items-center justify-between"><div className="flex items-center space-x-10"><span className="text-xl font-semibold text-indigo-900">Meridian<span className="text-emerald-500">.</span></span><div className="hidden md:flex space-x-8"><span className="text-sm text-slate-600 hover:text-indigo-900 cursor-pointer font-medium">Solutions</span><span className="text-sm text-slate-600 hover:text-indigo-900 cursor-pointer font-medium">Industries</span><span className="text-sm text-slate-600 hover:text-indigo-900 cursor-pointer font-medium">Resources</span></div></div><div className="flex items-center space-x-4"><button className="text-sm font-medium text-indigo-900">Contact Sales</button><button className="h-11 px-6 text-sm font-medium text-white bg-indigo-900 hover:bg-indigo-800 rounded-lg">Request Demo</button></div></div></nav>
      <section className="max-w-7xl mx-auto px-6 py-28"><div className="max-w-3xl"><div className="text-sm font-medium text-emerald-600 mb-4 uppercase tracking-wider">Enterprise Platform</div><h1 className="text-5xl font-bold text-indigo-900 mb-6 leading-tight">Transform your business operations at scale</h1><p className="text-xl text-slate-600 mb-10 leading-relaxed">Trusted by Fortune 500 companies to streamline workflows and drive measurable growth.</p><div className="flex space-x-4"><button className="h-12 px-8 text-sm font-medium text-white bg-indigo-900 rounded-lg">Schedule a Demo</button><button className="h-12 px-8 text-sm font-medium text-indigo-900 bg-white border border-indigo-200 rounded-lg">Case Studies</button></div><div className="flex items-center space-x-8 mt-12 pt-8 border-t border-slate-200"><div><span className="text-3xl font-bold text-indigo-900">500+</span><p className="text-sm text-slate-500">Enterprise clients</p></div><div><span className="text-3xl font-bold text-indigo-900">99.9%</span><p className="text-sm text-slate-500">Uptime SLA</p></div><div><span className="text-3xl font-bold text-indigo-900">$2.3B</span><p className="text-sm text-slate-500">Revenue processed</p></div></div></div></section>
      <section className="max-w-7xl mx-auto px-6 py-16"><div className="text-sm font-medium text-emerald-600 mb-2 uppercase tracking-wider">Why Meridian</div><h2 className="text-3xl font-bold text-indigo-900 mb-12">Built for enterprise complexity</h2><div className="grid grid-cols-1 md:grid-cols-3 gap-8">{[{t:"Compliance",d:"SOC 2, GDPR, HIPAA ready.",i:"🛡️"},{t:"Analytics",d:"Real-time dashboards with custom KPIs.",i:"📈"},{t:"Enterprise SSO",d:"SAML 2.0, Active Directory out of the box.",i:"🔐"}].map((f)=>(<div key={f.t} className="bg-white rounded-xl p-8 shadow-sm border border-slate-200"><div className="w-12 h-12 bg-indigo-50 rounded-lg flex items-center justify-center text-2xl mb-5">{f.i}</div><h3 className="text-lg font-semibold text-indigo-900 mb-3">{f.t}</h3><p className="text-sm text-slate-600 leading-relaxed">{f.d}</p></div>))}</div></section>
      <footer className="bg-indigo-900 mt-16"><div className="max-w-7xl mx-auto px-6 py-12 flex justify-between items-center"><span className="text-sm text-indigo-300">© 2026 Meridian Technologies</span><div className="flex space-x-6 text-sm text-indigo-300"><span className="hover:text-white cursor-pointer">Privacy</span><span className="hover:text-white cursor-pointer">Terms</span></div></div></footer>
    </div>
  )
}
