export default function AgencyBrutalistDemo() {
  return (
    <div className="min-h-screen bg-white" style={{fontFamily:"Space Mono, monospace"}}>
      <link href="https://fonts.googleapis.com/css2?family=Space+Mono:wght@400;700&display=swap" rel="stylesheet"/>
      <nav className="border-b-4 border-black"><div className="max-w-6xl mx-auto px-4 h-16 flex items-center justify-between"><span className="text-xl font-bold uppercase tracking-wider">HAUS_</span><div className="hidden md:flex space-x-6"><span className="text-sm font-bold uppercase hover:bg-red-500 hover:text-white px-2 cursor-pointer">Work</span><span className="text-sm font-bold uppercase hover:bg-red-500 hover:text-white px-2 cursor-pointer">About</span><span className="text-sm font-bold uppercase hover:bg-red-500 hover:text-white px-2 cursor-pointer">Contact</span></div><button className="h-10 px-6 text-sm font-bold text-white bg-red-600 hover:bg-black border-2 border-black uppercase tracking-wider">Hire us</button></div></nav>
      <section className="max-w-6xl mx-auto px-4 py-24"><h1 className="text-8xl font-bold leading-none uppercase">WE<br/>MAKE<br/>THINGS<br/><span className="text-red-600">LOUD.</span></h1><p className="text-lg mt-8 max-w-md border-l-4 border-red-600 pl-4">Digital agency for brands that refuse to whisper. Strategy. Design. Development. No fluff.</p></section>
      <section className="max-w-6xl mx-auto px-4 py-16"><h2 className="text-3xl font-bold uppercase border-b-4 border-black pb-4 mb-12">Selected work_</h2><div className="grid grid-cols-1 md:grid-cols-2 gap-0">{[{t:"REVOLT BRAND",c:"Branding",y:"2026"},{t:"NEON LABS",c:"Web Dev",y:"2025"},{t:"ZERO STUDIOS",c:"Full Identity",y:"2025"},{t:"RAW COLLECTIVE",c:"Campaign",y:"2024"}].map((p)=>(<div key={p.t} className="border-2 border-black p-8 hover:bg-red-500 hover:text-white transition-colors group"><span className="text-xs font-bold uppercase tracking-wider opacity-50">{p.c} — {p.y}</span><h3 className="text-2xl font-bold uppercase mt-2">{p.t}</h3><span className="text-sm font-bold uppercase mt-4 inline-block group-hover:text-white">View project →</span></div>))}</div></section>
      <section className="bg-black text-white py-20"><div className="max-w-6xl mx-auto px-4"><h2 className="text-4xl font-bold uppercase mb-8">The team_</h2><div className="grid grid-cols-1 md:grid-cols-4 gap-0">{[{n:"ANA K.",r:"Creative Director"},{n:"MAX R.",r:"Lead Developer"},{n:"JULES T.",r:"Strategist"},{n:"SAMI L.",r:"Designer"}].map((m)=>(<div key={m.n} className="border border-white/20 p-6"><div className="w-16 h-16 bg-red-600 mb-4"></div><h3 className="text-lg font-bold uppercase">{m.n}</h3><p className="text-sm text-white/60 uppercase">{m.r}</p></div>))}</div></div></section>
      <footer className="border-t-4 border-black"><div className="max-w-6xl mx-auto px-4 py-8 flex justify-between"><span className="text-sm font-bold uppercase">© 2026 HAUS_</span><span className="text-sm font-bold uppercase">hello@haus.agency</span></div></footer>
    </div>
  )
}
