export default function SaaSPlayfulDemo() {
  return (
    <div className="min-h-screen bg-amber-50" style={{ fontFamily: "Nunito, sans-serif" }}>
      <link href="https://fonts.googleapis.com/css2?family=Nunito:wght@400;600;700;800&display=swap" rel="stylesheet" />
      <nav className="bg-white/80 backdrop-blur-sm border-b border-amber-200"><div className="max-w-6xl mx-auto px-4 h-16 flex items-center justify-between"><span className="text-xl font-extrabold text-violet-600">boop! 🎉</span><div className="hidden md:flex space-x-6"><span className="text-sm text-slate-600 hover:text-violet-600 cursor-pointer font-semibold">Features</span><span className="text-sm text-slate-600 hover:text-violet-600 cursor-pointer font-semibold">Pricing</span><span className="text-sm text-slate-600 hover:text-violet-600 cursor-pointer font-semibold">Blog</span></div><button className="h-10 px-6 text-sm font-bold text-white bg-gradient-to-r from-violet-500 to-pink-500 rounded-full shadow-lg shadow-violet-200">Let&apos;s go! 🚀</button></div></nav>
      <section className="max-w-6xl mx-auto px-4 py-24 text-center"><div className="inline-flex items-center px-4 py-2 rounded-full bg-violet-100 text-violet-700 text-sm font-bold mb-6">🎈 Free for small teams!</div><h1 className="text-6xl font-extrabold text-slate-900 mb-6 leading-tight">Make work feel<br/>like <span className="text-transparent bg-clip-text bg-gradient-to-r from-violet-500 to-pink-500">play</span> ✨</h1><p className="text-lg text-slate-600 max-w-xl mx-auto mb-8 font-medium">The friendliest project tool ever. Pinky promise. 🤙</p><div className="flex justify-center space-x-3"><button className="h-12 px-8 text-sm font-bold text-white bg-gradient-to-r from-violet-500 to-pink-500 rounded-full shadow-lg shadow-violet-200">Try for free 🎉</button><button className="h-12 px-8 text-sm font-bold text-violet-700 bg-violet-100 rounded-full">Watch demo 📺</button></div></section>
      <section className="max-w-6xl mx-auto px-4 py-16"><div className="grid grid-cols-1 md:grid-cols-3 gap-6">{[{t:"Kanban boards 📋",d:"Drag, drop, done!",bg:"bg-pink-50 border-pink-200"},{t:"Team chat 💬",d:"GIFs, reactions, custom emoji!",bg:"bg-violet-50 border-violet-200"},{t:"Analytics 📊",d:"Pretty charts that make sense.",bg:"bg-amber-50 border-amber-200"}].map((f)=>(<div key={f.t} className={`rounded-2xl p-6 border-2 ${f.bg}`}><h3 className="text-lg font-extrabold text-slate-900 mb-2">{f.t}</h3><p className="text-sm text-slate-600 font-medium">{f.d}</p></div>))}</div></section>
      <section className="max-w-6xl mx-auto px-4 py-16"><h2 className="text-3xl font-extrabold text-slate-900 text-center mb-4">Simple pricing 💸</h2><p className="text-slate-600 text-center mb-12 font-medium">No surprises.</p><div className="grid grid-cols-1 md:grid-cols-2 gap-6 max-w-3xl mx-auto"><div className="bg-white rounded-2xl p-8 border-2 border-violet-200"><h3 className="text-lg font-extrabold text-slate-900">Free 🆓</h3><div className="mt-4 mb-6"><span className="text-4xl font-extrabold text-slate-900">$0</span><span className="text-slate-500 font-semibold">/mo</span></div><ul className="space-y-3 mb-8 text-sm text-slate-600 font-semibold"><li>🎯 5 projects</li><li>👥 5 members</li><li>💜 Community</li></ul><button className="w-full h-10 text-sm font-bold text-violet-700 bg-violet-100 rounded-full">Start free</button></div><div className="bg-gradient-to-br from-violet-500 to-pink-500 rounded-2xl p-8 text-white shadow-xl"><h3 className="text-lg font-extrabold">Pro 🌟</h3><div className="mt-4 mb-6"><span className="text-4xl font-extrabold">$12</span><span className="text-violet-200 font-semibold">/mo</span></div><ul className="space-y-3 mb-8 text-sm font-semibold text-violet-100"><li>🚀 Unlimited</li><li>🎨 Custom themes</li><li>⚡ Priority</li></ul><button className="w-full h-10 text-sm font-bold text-violet-700 bg-white rounded-full">Go Pro!</button></div></div></section>
      <footer className="bg-violet-900 mt-16"><div className="max-w-6xl mx-auto px-4 py-8 text-center"><span className="text-sm text-violet-300 font-semibold">Made with 💜 by boop! © 2026</span></div></footer>
    </div>
  )
}
